# Generated by Django 5.2 on 2025-07-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20250516_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='venue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
